apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-tapdemo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-tapdemo
spec:
  source:
    git:
      url: https://github.com/smachida/spring-petclinic-tapdemo.git
      ref:
        branch: main
        tag: tap-1.3
